[build-system]
requires = ["setuptools>=77.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "opngl"
version = "0.1.2"
description = "Motor gráfico y de interfaz de usuario de escritorio basado en Python y Vulkan"
readme = "README.md"
authors = [
    { name = "BluePanda" }
]
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Application Frameworks"
]
requires-python = ">=3.8"
dependencies = [
    "vulkan",
    "cffi",
    "glfw",
    "pillow",
    "miniaudio"
]

[tool.setuptools.packages.find]
include = ["opngl*"]

[tool.setuptools.package-data]
opngl = [
    "shaders/*.vert",
    "shaders/*.frag",
    "resources/fonts/*.ttf",
    "resources/images/*",
    "resources/sounds/*"
]